### ISSUE TITLE
Alert has an unrecognized area

### ISSUE THREAD

**Issue by eliadab1** [amitfin/oref_alert#103]
### System Health details

homeassistant    | 2024-09-15 11:28:43.516 ERROR (MainThread) [custom_components.oref_alert] Alert has an unrecognized area: מיני ישראל - נחשון

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/amitfin/oref_alert/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

homeassistant    | 2024-09-15 11:28:43.516 ERROR (MainThread) [custom_components.oref_alert] Alert has an unrecognized area: מיני ישראל - נחשון

I leave near netanya

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
homeassistant    | 2024-09-15 11:28:43.516 ERROR (MainThread) [custom_components.oref_alert] Alert has an unrecognized area: מיני ישראל - נחשון
```

**Comment by amitfin** [comment]
The log entry is correct since there is not such an area of "מיני ישראל - נחשון", yet Pikud HaOref reports and alert in this nonexistent area:
![image](https://github.com/user-attachments/assets/a62783cb-502b-4148-a306-2e23eedbb6a6)
<img width="1160" alt="image" src="https://github.com/user-attachments/assets/f5d0e11f-8832-4dd1-bf77-1b2367c37ead">

However, there was an issue of flooding the log with the same entry over and over again. [v2.12.1](https://github.com/amitfin/oref_alert/releases/tag/v2.12.1) fixed that.

**Comment by eliadab1** [comment]
thanx

**Comment by mbrevda** [comment]
Is there a recommended way to deal with new/unknown areas? I see other apps have the data, but not sure the HFC is providing it? As an example: `מלון פרא`
