### ISSUE TITLE
Any desire to get this into core?

### ISSUE THREAD

**Issue by jeeftor** [amitfin/oref_alert#107]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/amitfin/oref_alert/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I've written a few integrations into CORE an I was wondering if you'd like to partner to get this integrate into CORE instead of as a HACS module...

### Describe the solution you'd like

I'd be happy to work with you to get this into home assistant core

### Describe alternatives you've considered

N/A

### Additional context

I've done a bunch of core integrations

**Comment by amitfin** [comment]
A few thoughts:
1) No question that it will be better to have the integration built-in in HA. I'm in favor.
2) I've also contributed to HA, but will be happy to get your help.
3) In general, the integration doesn't require more work (AFAIK). It also has a good code coverage, so testing shouldn't be an issue.
4) We should understand HA core team stand about it. It's country specific. Pikud HaOref website is blocked for IP addresses outside of Israel. In addition, there might be some political angles (which I hope can be avoided).
5) Updating the metadata has some complications: there is a [daily GH action](https://github.com/amitfin/oref_alert/blob/9602761e8b2102dc691aca9f8e248fbb58301d7b/.github/workflows/metadata.yml#L29) which checks if there are any changes. However, since Pikud HaOref website is blocked for IP addresses outside of Israel and GH actions are running outside of Israel, the action uses a dedicated [(authenticated) proxy](https://github.com/amitfin/oref_alert/blob/main/scripts/squid/squid.conf) which is hosted in my house. Not sure HA core should have such a dependency.

Would love to get your thoughts and see if we can push it forward.

**Comment by jeeftor** [comment]
So I guess I'd have to VPN in to test it, which is fine. The real hold up with getting things into core is they want small PR's full test coverage and you can only work on one domain at a time.  

So like start with binary_sensor or normal sensor etc. 

I believe there are already country specific integrations but I can ping one or the mods to confirm. 

I haven't looked too hard at the work but I was bored - and needed a project and figured as a jew - this project might do.

**Comment by jlrosssc** [comment]
With the website blocked, is this integration not useable outside of Israel?

**Comment by amitfin** [comment]
Yes, the integration can't be used outside of Israel as the data source (URL) is only accessible from the country (probably for minimizing attack surface.)
Anyway, given the experience from the last few days it's probably better to keep it as a standalone (custom) integration. It allows more flexibility for releasing updates. In some cases the updates are related to changes in the source of the data and it's not predictable. Timing can be very critical so waiting for the next (minor) update of HA core can be a real blocker.
