### ISSUE TITLE
False alarm, no alarm in israel while the sensor detects motion 

### ISSUE THREAD

**Issue by nir-f** [amitfin/oref_alert#136]
### System Health details

.

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/amitfin/oref_alert/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Today at 03:35 motion was detected while there was nothing real, just false alarm.
Also the detection was cleared after 4 seconds and not after 10 minutes, means it's a weird glitch.

My setup is for Ramat Hasharon
I added image from history 
![IMG_6834](https://github.com/user-attachments/assets/5c59b4aa-75bb-42bb-9644-4d3864ae48c5)

### Reproduction steps

1.
2..
3.
...

### Debug logs

```text
No logs
```

**Comment by nir-f** [comment]
Version is 2.15.2

**Comment by Itay080** [comment]
I've experienced the same thing at the same time

**Comment by amitfin** [comment]
I've also experienced the same problem at the same time (I'm from Petah Tikva):
![image](https://github.com/user-attachments/assets/b51c87d9-3072-4fb4-b4f5-987832eea6f7)

It seems that the glitch was on the servers of Pikud HaOref and for a few seconds some or all areas had a false alarm (which got deleted after less than 5 seconds). I'll try to report it to Pikud HaOref so they can investigate the root cause on their side.

@nir-f , as a side note: based on the type of the binary sensor (`motion` and not `safety`), your version is earlier than [v2.10.0](https://github.com/amitfin/oref_alert/releases/tag/v2.10.0) which was released on Nov 13, 2023. Please double check the installed version. (Maybe the type of the binary sensor was changed manually, but it's unlikely.)
