### ISSUE TITLE
Supplemental alert data

### ISSUE THREAD

**Issue by mbrevda** [amitfin/oref_alert#9]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/amitfin/oref_alert/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Would be great to have additional data on the sensors

### Describe the solution you'd like

Overlay data from other feeds

### Describe alternatives you've considered

Doing this as a mess of sensors and templates

### Additional context

There is more data that can be useful related to alerts and general Home Front command directions. I'm sure your familiar with these api's, opening this as a starting point for a discussion:

- [district data](https://www.oref.org.il//Shared/Ajax/GetDistricts.aspx?lang=he) can show general location and time to get to a shelter. Useful to keep an eye on the general country-wide situation
- replacing (or supplementing) `alert.category`  with `category` [from here](https://www.oref.org.il//Shared/Ajax/GetAlertCategories.aspx) can give more detail than the current `category`. It can also be used to add icons based on the `category`. Icons can be useful on dashboards to help quantify the alert type
- Instructions for what to do based on the alert can be found [here](https://www.oref.org.il/Leftovers/HE.Leftovers.json). This can be especially useful for selected areas
- City-specific instructions can be added from [here](https://www.oref.org.il/Shared/Ajax/GetCityNotes.aspx?lang=he&citycode=xxx) (replace `citycode`). This can also be useful for selected areas.

These api's don't need to be polled continuously, it would probably suffice to load them only on startup (and perhaps refresh once every 24 hours).

All in all, this integration has been beneficial towards keeping everyone a bit safer and more up-to-date - thanks!

**Comment by amitfin** [comment]
Great ideas! Thanks!
Here is my plan for implementation. Before jumping into it, would love to hear your thoughts on the concrete plan:
1. Add "Get To Shelter" attribute which will be a map with key="area name" and value="amount of seconds". The map will contain only the selected areas of the sensor.
2. Add to every alert "categoryCode" (from [here](https://www.oref.org.il//Shared/Ajax/GetAlertCategories.aspx)) and "categoryDescription" (from [here](https://www.oref.org.il/Leftovers/HE.Leftovers.json)) in addition to "category" (which is a number). Note that "categoryDescription" might be missing in some cases, as the file doesn't cover all categories.

I'm still not sure about city-specific instructions. The data is not so structured. It has "note1", "note2" and "note3" with most of the data, but there are many other fields which might be used in specific cases.

**Comment by mbrevda** [comment]
Sounds good! `timeToShelter` could be extremely useful. Not sure it needs to be a map per se, but either way is fine. Re #2, I realized there may not be a 1:1 mapping. For example, there doesn't seem to be a category for terrorist infiltration (unless I missed it, it seems that category 1 - along with incoming missiles).

You are right that city-specific instructions are less useful than real-time alerts. They can be useful though in markdown cards though, and would seem like they can really round out this integration.

**Comment by amitfin** [comment]
This is eventually what was implemented:
- A new sensor (not binary sensor) which holds the time (seconds) to shelter:
  - If there is no active alert in the area, the value of the sensor is "unknown". 
  - When a new alert starts, the initial time to shelter is according to the metadata coming from Pikud Haoref (e.g. 90 seconds in the middle of the country). The counter goes down as time passes, until -60 seconds (1 minute past due).
  - The new sensor also has an attribute "Time To Shelter" which holds the constant value for the time to shelter in the area (e.g. 90).
  - This sensor is created for every binary sensor (primary or secondary) unless the corresponding sensor has multiple areas (including districts and large cities ("כל האזורים"). The reason is that with multiple areas it's possible that there are multiple alerts with different timestamps, so it's not possible to count the time in a unique way (even if they share the same value for the "time to shelter" metadata). This is not a critical limitation, as it's always possible to create an additional sensor for the specific area of interest.
- The "categoryCode" was not added. After thinking about it some more, I don't see a lot of value for adding it. The alert already has "category" (an integer), so adding an equivalent string doesn't add here a lot.

The new sensors require v2.3.0.

**Comment by mbrevda** [comment]
> This is eventually what was implemented

Greatly appreciated and very useful features.

The idea in this feature request was to make district data and time to shelter available for all items,  including those `country_alerts` list. Being that that data is already available to the integration, would you consider adding it?

**Comment by amitfin** [comment]
I didn't want to add additional information to the lists since I got feedback that they are overloaded and no easy to read. Obviously, with a dedicated view it's possible to create a nicer view of those lists, but the built-in viewer (the `state` dialog) doesn't present them cleanly. Adding more information there will make the lists even harder to navigate and read.

BTW, can you elaborate on the thing you are trying to achieve? What is the purpose of understanding the "time to shelter" of any alert in the country? Maybe if I better understand the need, we can figure out a solution.

**Comment by mbrevda** [comment]
Sure - currently I have a markdown card that looks like this:
<img width="398" alt="Screenshot 2023-10-30 at 10 27 49 AM" src="https://github.com/amitfin/oref_alert/assets/293004/4f6b436a-7f9f-4b0b-ab0f-bc3b89e3abc7">

I'd like to add the district name, and the time to shelter (help provide context on the location for those less familiar with places in Israel). Something like this:

<img width="397" alt="Screenshot 2023-10-30 at 10 30 22 AM" src="https://github.com/amitfin/oref_alert/assets/293004/28ab83d5-dc83-4b59-b1b9-a7cc75214fd8">

**Comment by amitfin** [comment]
I can expose the metadata as custom services (which now can return data). Will it help?

**Comment by amitfin** [comment]
Another option is to have the metadata information in your card. I can generate it for you (there is already a script which does it).

**Comment by mbrevda** [comment]
not sure if services can be consumed in markdown? I could also see this working as a [macro](https://www.home-assistant.io/blog/2023/04/05/release-20234/#macros-for-your-templates)

Ultimately, all this is solvable via

> [Doing this as a mess of sensors and templates](https://github.com/amitfin/oref_alert/issues/9#:~:text=Describe%20alternatives%20you%27ve%20considered)

The cleanest/simplest and most straightforward seem to be to add the data directly to the entities map so that they are available directly on the entity.

**Comment by amitfin** [comment]
Do you use only templates or also JS for the UI element?
If you have JS code, you can import the metadata information to JS using these instructions:
1. The location of the metadata Python dictionaries are [here](https://github.com/amitfin/oref_alert/tree/main/custom_components/oref_alert/metadata).
2. Convert the Python file(s) to JS using a convertor like [this one](https://extendsclass.com/python-to-javascript.html) (but there are many other similar tools out there). 
3. Add the JS files to your UI component.

**Comment by mbrevda** [comment]
It would be a lot simpler for me to create my own service that offers all this (out of home assistant) and just import it as an iframe! That would give me all the data and flexibility I want, including styling not available in HA (such as this [icon](https://www.creativefabrica.com/product/terrorist-terrorism-icon-2/))!

I understand if you don't want to add it. I hope you reconsider. Either way, thanks for this!

**Comment by mbrevda** [comment]
Can we revisit this?

> If you use the markdown card, you can create a similar solution to the above JS instructions, but as a Jinja macro which (for example) gets the name of the area and returns the time to shelter. The macro file should contain the dictionary.

I was wondering if there was some way for an integration to supply a macro? It seems this integration already includes all of the necessary data, how hard would it be to expose it somehow?
